name: Update repos
on:
  schedule:
    - cron:  '1 3 * * *'
jobs:
  updateBrews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update repos
        run: |
          cat .updatestrings|awk '{print $1}'|SILENT_UPDATE=1 xargs -L1 -I{} ./update {}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update brews
          title: Update repos
          body: Update version of brews
          branch: update-brews
